### ISSUE TITLE
Output size is 3X larger than the input size

### ISSUE THREAD

**Issue by mukswilly** [deepmedia/Transcoder#105]
Just like in the title. My very first usage yielded a 6.12mb file from a 2.1mb file

**Comment by moxgeek** [comment]
your code please

**Comment by gvravikumar** [comment]
you need to use video strategies. like this...

            .setVideoTrackStrategy(
                DefaultVideoStrategy.Builder()
                    .addResizer(PassThroughResizer())
                    .addResizer(FractionResizer(1F / 3F))
                    .addResizer(AtMostResizer(500))
                    .frameRate(24) // .keyFrameInterval(4F)
                    .build()
            )

**Comment by natario1** [comment]
(Pasted to all my answers today: it's been a long time since my last issues review. I am sorry about the delay and I know you likely have moved on by now. Still, I'm going to answer where I can)

As in comments, the video strategy gives you many options to control size. In some cases, the default values may indeed increase the input size.
