### ISSUE TITLE
Trim without compression possible.?

### ISSUE THREAD

**Issue by arunkr83** [deepmedia/Transcoder#109]
Any way to do compression first then trim or trim without compression..?

**Comment by natario1** [comment]
(Pasted to all my answers today: it's been a long time since my last issues review. I am sorry about the delay and I know you likely have moved on by now. Still, I'm going to answer where I can)

No, for exact trimming we need to decode the video files because your chosen location may not be a video sync frame. So transcoding is necessary. But that doesn't mean you will lose quality. If you have a more specific problem with compression, let me know.
