### ISSUE TITLE
 Failed to stop the muxer

### ISSUE THREAD

**Issue by maunishWisdomlogix** [deepmedia/Transcoder#145]

**Comment by jumperson** [comment]
May be fix this issue by #159.

**Comment by mycohbasilan** [comment]
try adding TrackType to your DataSource

**Comment by junghonkim** [comment]
what's mean trackType to yout dataSource?
i got same issue from andorid os 9 device.
i used below code. 

```
 val mTranscodeVideoStrategy = DefaultVideoStrategy.exact(1080, 720).build()
 val transcodingFile = createTempOutputFile(context, MP4_SUFFIX)
 val builder = Transcoder.into(transcodingFile.absolutePath)
 val source = UriDataSource(context, uploadVideo.url.toUri())
 builder.addDataSource(source)
  ... 
.setVideoTrackStrategy(mTranscodeVideoStrategy).transcode()
```

**Comment by natario1** [comment]
(Pasted to all my answers today: it's been a long time since my last issues review. I am sorry about the delay and I know you likely have moved on by now. Still, I'm going to answer where I can)

This is a bit too generic to be actionable. If you want please open a new issue and provide details (sample video and code).
