### ISSUE TITLE
Feature Request : Overlay Audio over Video(already containing Audio)

### ISSUE THREAD

**Issue by pawaom** [deepmedia/Transcoder#152]
Currently this code allows only to replace or remove audio of video, there is no support for overlaying audio over video which already has audio. 

According to this

https://developer.android.com/reference/android/media/MediaMuxer#History ,

now Muxing Multiple Video/Audio Tracks is allowed for Api 26 and higher for an mp4 container.

I have been looing for examples , about using this feature, but cannot find any code. Can you please provide sample code and include this feature in future releases.

**Comment by natario1** [comment]
(Pasted to all my answers today: it's been a long time since my last issues review. I am sorry about the delay and I know you likely have moved on by now. Still, I'm going to answer where I can)

We don't plan to add this feature for now, sorry.
"Muxing multiple audio tracks" as in your link, does not mean blending them together. They get two entries in the MP4 container, but only one of them is played. It may be used, for example, to add multiple languages to a movie.
