### ISSUE TITLE
Increase key/sync frames

### ISSUE THREAD

**Issue by HBiSoft** [deepmedia/Transcoder#156]
Is it possible to specify how many sync frames there should be in the output video (or time between sync frames)?

I know it's possible to pass `MediaFormat.KEY_I_FRAME_INTERVAL` to `MediaFormat`, as shown below:

```kotlin
// 1 second between key frames!
mediaFormat.setInteger(MediaFormat.KEY_I_FRAME_INTERVAL, 1)
```

**Comment by natario1** [comment]
(Pasted to all my answers today: it's been a long time since my last issues review. I am sorry about the delay and I know you likely have moved on by now. Still, I'm going to answer where I can)

The option you are (were) looking for is called [keyFrameInterval](https://opensource.deepmedia.io/transcoder/track-strategies#other-options).
