### ISSUE TITLE
H265 support?

### ISSUE THREAD

**Issue by arianaa30** [deepmedia/Transcoder#157]
I would like to simply convert a H264 video to H265 codec. Is this encoding supported?

**Comment by danielgindi** [comment]
`MIMETYPE_VIDEO_HEVC`

**Comment by natario1** [comment]
(Pasted to all my answers today: it's been a long time since my last issues review. I am sorry about the delay and I know you likely have moved on by now. Still, I'm going to answer where I can)

You can use VideoStrategy's mimeType() function and pass 
https://developer.android.com/reference/android/media/MediaFormat#MIMETYPE_VIDEO_HEVC as suggested.
