### ISSUE TITLE
video trimming issue

### ISSUE THREAD

**Issue by expertBrains** [deepmedia/Transcoder#172]
Unexpected error while transcoding.
java.lang.IllegalStateException: Failed to stop the muxer

getting this error during trim video in android 8,9,10 .

**Comment by natario1** [comment]
(Pasted to all my answers today: it's been a long time since my last issues review. I am sorry about the delay and I know you likely have moved on by now. Still, I'm going to answer where I can)

This is a bit too generic to be actionable. If you still have this problem please provide sample video and your code, so I can reproduce on my own.
