### ISSUE TITLE
How to get demo app?

### ISSUE THREAD

**Issue by HaiziIzzudin** [deepmedia/Transcoder#185]
Hi, sorry for asking this simple question, but I'd love to test this project. Where can I get the demo app? If it build from source, can you give me steps to build it?
Thanks!

**Comment by natario1** [comment]
(Pasted to all my answers today: it's been a long time since my last issues review. I am sorry about the delay and I know you likely have moved on by now. Still, I'm going to answer where I can)

Hi, the demo app is in the `demo` folder. You can just open the project in Android Studio and after sync it will be ready to run.
