### ISSUE TITLE
[feature request] extracting frames (by timestamp) and creating video out of frames (with input / output framerate)

### ISSUE THREAD

**Issue by kibotu** [deepmedia/Transcoder#23]

**Comment by andrewcking** [comment]
I could also use video from bitmap frames functionality. Anyone have insight for the best way to go about this?

**Comment by natario1** [comment]
If you have OpenGL experience, you can set a `TimeInterpolator` that is currently invoked at each frame with the frame timestamp as argument. When it is invoked you can use `glReadPixels()` to get an array of image data and then a Bitmap.

**Comment by natario1** [comment]
(Preface: it's been a long time since my last issues review. I am sorry about the delay and I know you have moved on by now. Still, I'm going to answer where I can)

The thumbnailer class should help with extracting the image frames and resolve the first half of the problem. About frame-to-video mechanism, I consider that out of scope for now, sorry.
