### ISSUE TITLE
File Size is increased after transcode in some phones ex:Samsung S8 Device

### ISSUE THREAD

**Issue by rajkumarsavu** [deepmedia/Transcoder#69]
Actually I have uploaded 206MB video to transcode it gives 900MB video back as a result.
Please find below strategy which I have used

###  
                       DefaultVideoStrategy mTranscodeVideoStrategy = new DefaultVideoStrategy.Builder()
                        .addResizer(new AspectRatioResizer(16F / 9F))
                        .addResizer(new FractionResizer(1F))
                        .frameRate(24)
                        .bitRate(Math.min(Integer.parseInt(s), 1000000))
                        .keyFrameInterval(100)
                        .build(); 
======================================================
###  
                        mTranscodeFuture = Transcoder.
                        into(file.getAbsolutePath())
                        .addDataSource(context, mediaUri)
                        .setVideoTrackStrategy(mTranscodeVideoStrategy)
                        .transcode();
=========================================================

please help me out thank you in advance.

**Comment by natario1** [comment]
(Note: it's been a long time since my last issues review. I am sorry about the delay and I know you have moved on by now. Still, I'm going to answer where I can)

It's hard to say what happened but keyFrameInterval(100) seems extremely high and maybe it's interpreted wrongly by the codec. Should try with lower values like 3. Closing this anyway because it's so old, feel free to re-open.
